spring.cloud.config.enabled=false
spring.cloud.config.import-check=false
spring.main.lazy-initialization=true
# Añade cualquier otra cosa que intente conectar a red (Eureka, etc)
spring.cloud.discovery.enabled=false