spring:
  application:
    name: Admin

    # ELIMINADO PARA QUE NO DEPENDA DEL CONFIG
  cloud:
     config:
       enabled: false

  # para que Admin se vea a sí mismo
  boot:
    admin:
      context-path: /admin
      ui:
        public-url: http://localhost:9090/admin
      client:
        # DEBE terminar en /admin
        url: "http://admin-server:9090/admin"
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
    env:
      show-values: always
      post:
        enabled: true
