server:
  port: 8080

spring:
  boot:
    admin:
      client:
        # DEBE terminar en /admin si esa es la base del server
        url: "http://admin-server:9090/admin"
        instance:
          # Esto ayuda a que el Admin sepa cómo volver a llamar al microservicio
          prefer-ip: true
#          metadata:
#            user.name: "${spring.security.user.name:admin}"
#            user.password: "${spring.security.user.password:admin}"
  cloud:
    gateway:
      #      EUREKA DESACTIVADO
      #      discovery:
      #        locator:
      #          enabled: true # Permite localizar servicios por su nombre en Eureka
      routes:
#        EJEMPLO RUTAS (sin Eureka)
#        - id: usuarios-service
#          uri: http://usuarios-ms:8081
#          predicates:
#            - Path=/api/usuarios/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: usuariosCB
#                fallbackUri: forward:/fallback/usuarios

# Configuración de Resiliencia (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      usuariosCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

# Observabilidad y Logs
management:
  tracing:
    sampling:
      probability: 1.0 # 100% de trazas para desarrollo
  endpoints:
    web:
      exposure:
        include: "*" # Exponemos todo para Spring Boot Admin

