# Este archivo lo lee el Config Service y se lo da a TODOS
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
      post:
        enabled: true