server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native # Perfil para leer archivos locales en lugar de Git
  cloud:
    config:
      server:
        native:
          # Busca los archivos en una carpeta interna del proyecto
          search-locations: file:/app/config-repo/
    refresh:
      enabled: false # Desactiva la infraestructura de Refresh que falla en AOT
  boot:
    admin:
      client:
        url: "http://admin-server:9090/admin"


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    # El config service debe esperar a registrarse antes de ser usado
    fetch-registry: false
    register-with-eureka: false
    enabled: false # Mantener habilitado para que se registre
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, bus-refresh # Habilita el refresco por colas