spring:
  boot:
    admin:
      client:
        # DEBE terminar en /admin si esa es la base del server
        url: "http://admin-server:9090/admin"

  application:
    name: api-gateway-v3
  config:
    # Importa la configuración desde el Config Service usando su nombre en Docker/Eureka
    import: "optional:configserver:http://config-service-v3:8888"
  cloud:
    refresh:
      enabled: false # Desactiva la infraestructura de Refresh que falla en AOT